language: go

go:
  - 1.0.2
  - 1.0.3
  - 1.1
  - 1.2
  - 1.3
  - tip

before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "local     all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "local     all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostnossl all         pqgossltest 127.0.0.1/32          reject" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostnossl all         pqgosslcert 127.0.0.1/32          reject" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostssl   all         pqgossltest 127.0.0.1/32          trust"  >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostssl   all         pqgosslcert 127.0.0.1/32          cert"  >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host      all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostnossl all         pqgossltest ::1/128               reject" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostnossl all         pqgosslcert ::1/128               reject" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostssl   all         pqgossltest ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "hostssl   all         pqgosslcert ::1/128               cert" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host      all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo install -o postgres -g postgres -m 600 -t /var/lib/postgresql/$PGVERSION/main/ certs/server.key certs/server.crt certs/root.crt
  - [ "${PGVERSION}" == "8.4" ] || [ "${PGVERSION}" == "9.0" ] || (echo "ssl_cert_file = 'server.crt'" | sudo tee -a /etc/postgresql/$PGVERSION/main/postgresql.conf)
  - [ "${PGVERSION}" == "8.4" ] || [ "${PGVERSION}" == "9.0" ] || (echo "ssl_key_file = 'server.key'" | sudo tee -a /etc/postgresql/$PGVERSION/main/postgresql.conf)
  - [ "${PGVERSION}" == "8.4" ] || [ "${PGVERSION}" == "9.0" ] || (echo "ssl_ca_file = 'root.crt'" | sudo tee -a /etc/postgresql/$PGVERSION/main/postgresql.conf)
  - sudo ls -l /var/lib/postgresql/$PGVERSION/main/
  - sudo cat /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo chmod og-xwr certs/postgresql.key
  - sudo /etc/init.d/postgresql restart

env:
  matrix:
    - PGVERSION=9.3
    - PGVERSION=9.2
    - PGVERSION=9.1
    - PGVERSION=9.0
    - PGVERSION=8.4

script:
 - env PQSSLCERTTEST_KEY=$PWD/certs/postgresql.key PQSSLCERTTEST_CERT=$PWD/certs/postgresql.crt PQGOSSLTESTS=1 PGUSER=postgres go test -v ./...

before_script:
 - psql -c 'create database pqgotest' -U postgres
 - psql -c 'create user pqgossltest' -U postgres
 - psql -c 'create user pqgosslcert' -U postgres
